[package]
name = "observus_server"
version = "0.1.0"
edition = "2024"

[dependencies]
observus_common = { path = "../common" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
